import { Category } from '@/types/menu.types';

export const sampleCategories: Category[] = [
  {
    id: '1',
    name: 'Chaufas',
    description: 'Arroces fritos con ingredientes variados',
    isActive: true,
    dishCount: 2,
    icon: '🍚',
    color: '#F59E0B',
    order: 1,
  },
  {
    id: '2',
    name: 'Tallarines',
    description: 'Pasta china salteada con diferentes carnes y verduras',
    isActive: true,
    dishCount: 2,
    icon: '🍜',
    color: '#DC2626',
    order: 2,
  },
  {
    id: '3',
    name: 'Entradas',
    description: 'Aperitivos y entradas tradicionales chinas',
    isActive: true,
    dishCount: 1,
    icon: '🥟',
    color: '#10B981',
    order: 3,
  },
  {
    id: '4',
    name: 'Sopas',
    description: 'Caldos calientes con wantanes y fideos',
    isActive: true,
    dishCount: 1,
    icon: '🥣',
    color: '#3B82F6',
    order: 4,
  },
  {
    id: '5',
    name: 'Especialidades',
    description: 'Platos especiales de la casa',
    isActive: true,
    dishCount: 2,
    icon: '👨‍🍳',
    color: '#8B5CF6',
    order: 5,
  },
  {
    id: '6',
    name: 'Bebidas',
    description: 'Refrescos y bebidas tradicionales',
    isActive: true,
    dishCount: 0,
    icon: '🥤',
    color: '#06B6D4',
    order: 6,
  },
];