import { Dish } from '@/types/menu.types';

export const sampleDishes: Dish[] = [
  {
    id: '1',
    name: 'Arroz Chaufa Especial',
    description: 'Arroz frito con pollo, cerdo, camarones, huevo y cebollín.',
    price: 25.90,
    image: '/dishes/chaufa-especial.jpg',
    categoryId: '1',
    categoryName: 'Chaufas',
    isAvailable: true,
    ingredients: ['Arroz', 'Pollo', 'Cerdo', 'Camarones', 'Huevo', 'Cebollín'],
    preparationTime: 15,
    isSpicy: false,
    isVegetarian: false,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Tallarín Saltado',
    description: 'Tallarines salteados con carne de res, pimientos, cebolla y salsa de soja.',
    price: 28.50,
    image: '/dishes/tallarin-saltado.jpg',
    categoryId: '2',
    categoryName: 'Tallarines',
    isAvailable: true,
    ingredients: ['Tallarines', 'Carne de res', 'Pimientos', 'Cebolla', 'Salsa de soja'],
    preparationTime: 20,
    isSpicy: true,
    isVegetarian: false,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    name: 'Wantán Frito',
    description: 'Masa rellena de carne de cerdo y pollo, frita hasta dorar perfectamente.',
    price: 18.90,
    image: '/dishes/wantan-frito.jpg',
    categoryId: '3',
    categoryName: 'Entradas',
    isAvailable: true,
    ingredients: ['Masa de wantán', 'Carne de cerdo', 'Carne de pollo'],
    preparationTime: 10,
    isSpicy: false,
    isVegetarian: false,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    name: 'Sopa Wantán',
    description: 'Caldo de pollo con wantanes rellenos de carne, cebollín y vegetales.',
    price: 22.00,
    image: '/dishes/sopa-wantan.jpg',
    categoryId: '4',
    categoryName: 'Sopas',
    isAvailable: true,
    ingredients: ['Caldo de pollo', 'Wantanes', 'Carne', 'Cebollín', 'Zanahoria'],
    preparationTime: 15,
    isSpicy: false,
    isVegetarian: false,
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    name: 'Pollo con Almendras',
    description: 'Trozos de pollo salteados con almendras, vegetales y salsa especial.',
    price: 32.00,
    image: '/dishes/pollo-almendras.jpg',
    categoryId: '5',
    categoryName: 'Especialidades',
    isAvailable: true,
    ingredients: ['Pollo', 'Almendras', 'Pimientos', 'Cebolla', 'Salsa especial'],
    preparationTime: 25,
    isSpicy: false,
    isVegetarian: false,
    createdAt: new Date('2024-01-18'),
  },
  {
    id: '6',
    name: 'Chijaukay',
    description: 'Pollo frito crocante con salsa agridulce china.',
    price: 26.50,
    image: '/dishes/chijaukay.jpg',
    categoryId: '5',
    categoryName: 'Especialidades',
    isAvailable: true,
    ingredients: ['Pollo', 'Harina', 'Huevo', 'Salsa agridulce'],
    preparationTime: 20,
    isSpicy: false,
    isVegetarian: false,
    createdAt: new Date('2024-01-14'),
  },
  {
    id: '7',
    name: 'Arroz Chaufa Vegetariano',
    description: 'Arroz frito con huevo, vegetales frescos y soya.',
    price: 21.90,
    image: '/dishes/chaufa-vegetariano.jpg',
    categoryId: '1',
    categoryName: 'Chaufas',
    isAvailable: true,
    ingredients: ['Arroz', 'Huevo', 'Zanahoria', 'Arvejas', 'Maíz', 'Soya'],
    preparationTime: 12,
    isSpicy: false,
    isVegetarian: true,
    createdAt: new Date('2024-01-16'),
  },
  {
    id: '8',
    name: 'Tallarín con Verduras',
    description: 'Tallarines salteados con mix de verduras frescas y salsa de ostras.',
    price: 24.00,
    image: '/dishes/tallarin-verduras.jpg',
    categoryId: '2',
    categoryName: 'Tallarines',
    isAvailable: true,
    ingredients: ['Tallarines', 'Brócoli', 'Zanahoria', 'Pimiento', 'Hongos', 'Salsa de ostras'],
    preparationTime: 18,
    isSpicy: false,
    isVegetarian: true,
    createdAt: new Date('2024-01-22'),
  },
];